---
title: "MNIST MLP"
output: html_document
date: "2023-12-29"
---

#setup
```{r}
library(keras)
```
#preprocess and split set into training/testing
```{r}
mnist <- dataset_mnist()
train_images <- mnist$train$x
train_labels <- mnist$train$y
test_images <- mnist$test$x
test_labels <- mnist$test$y
train_images <- array_reshape(train_images, c(nrow(train_images), 28 * 28)) / 255
test_images <- array_reshape(test_images, c(nrow(test_images), 28 * 28)) / 255
```
#convert to one-hot encoding
```{r}
train_labels <- to_categorical(train_labels, 10)
test_labels <- to_categorical(test_labels, 10)
```
# Build model
```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 512, activation = 'relu', input_shape = c(28 * 28)) %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 10, activation = 'softmax')
model %>% compile(
  optimizer = 'adam',
  loss = 'categorical_crossentropy',
  metrics = c('accuracy')
)
history <- model %>% fit(
  train_images, train_labels,
  epochs = 10, batch_size = 128,
  validation_split = 0.2
)
```
# checking
test_loss_and_metrics <- model %>% evaluate(test_images, test_labels, verbose = 0)
cat('Test accuracy:', test_loss_and_metrics$accuracy, '\n')

